version: '3'
services:
  mariadb:
    image: mariadb
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
      - ./MariaDB/data:/var/lib/mysql
